language: C
matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5 COMPILER=gnu
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - env: CXX=clang++-3.8 CC=clang-3.8 COMPILER=llvm
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
script:
    - cd src/openmp-threading
    - make
    - ./XSBench -s small -t 4
