language: c

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - llvm-dev

script:
    - echo $CC
    - $CC --version
    - cd src/openmp-threading
    - make
    - ./XSBench -s small -t 4
