name: HIP Tests

on:
  push:
    branches: [ master, 'pr/*' ]
  pull_request:
    branches: [ master ]

jobs:
  build-hip:
    runs-on: ubuntu-latest
    container: rocm/dev-ubuntu-22.04:5.4.2-complete
    env:
      DEBIAN_FRONTEND: noninteractive
      BACKEND: hip
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd $BACKEND; make -j4
